2023-04-26 14:50:25 [1m[31mERROR[0m HTTPSConnectionPool(host='nodgminatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=3%2BPaulay%2Bede%2BHungary&format=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019769FE9A58>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))