2023-04-26 13:02:16 [31m[1mERROR[0m HTTPSConnectionPool(host='noominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?street=3+cromwell+street&city=+stoke-on-trent&county=+&state=+&country=+&postalcode=+&format=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002211F5942B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))